### PR TITLE
Make port more explicit

### PR DESCRIPTION
**Pull request by clemisch**

### CODE REVIEW

**Comment by clemisch** [comment]
This is helpful when using yark on a headless server. I had to dig around to find the port.

**Comment by Owez** [comment]
Completed in 86fccb770cc98edc5e552bb64d00529ced881152 because of this PR :)

I've made host and port into cli arguments so you can now perform:

```
yark view --port=1234
yark view --host=9.8.7.6
```

The new release should be available on PyPI

**Comment by clemisch** [comment]
The implementation seems to be sensitive to the order of arguments:

```
$ yark view --ip=0.0.0.0 --port=7667 harry_podcast
Archive doesn't exist, please make sure you typed it's name correctly!
$ yark view harry_podcast --ip=0.0.0.0 --port=7667 
Starting viewer for harry_podcast..
```

I realize this project is a [home-cooked meal](https://www.robinsloan.com/notes/home-cooked-app/), but could you consider switching the argument handling to e.g. [argparse](https://docs.python.org/3/library/argparse.html)?

**Comment by Owez** [comment]
I would, I just dont have much time to dedicate to it at the moment with work, uni and another side project. It has been on the to-do list for a while now though. This project started out as a weekend project and ballooned out haha

**Pull request closed without merging**
